tasks:
  - init: |
      go mod tidy
      env GO111MODULE=on go install github.com/go-delve/delve/cmd/dlv@master
      mv "$(go env GOPATH)"/bin/dlv "$(go env GOPATH)"/bin/dlv-dap
      env GO111MODULE=on go install github.com/gopherdata/gophernotes@latest
    command: |
      mkdir -p ~/.local/share/jupyter/kernels/gophernotes
      cd ~/.local/share/jupyter/kernels/gophernotes
      cp "$(go env GOPATH)"/pkg/mod/github.com/gopherdata/gophernotes@v0.7.3/kernel/*  "."
      chmod +w ./kernel.json # in case copied kernel.json has no write permission
      sed "s|gophernotes|$(go env GOPATH)/bin/gophernotes|" < kernel.json.in > kernel.json
vscode:
  extensions:
    - golang.go
    - ms-toolsai.jupyter
    - ms-python.python
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
